export const sample_data = [
  {
    rt: 1585,
    stimulus:
      "<h3>Please read these instructions carefully!</h3> </br><p>For this experiment, please place your <b>left index finger on the 'e' key</b> and your <b>right index finger on the 'i' key</b>.</p><p> You will read sentences word by word. However, you will have to guess which word comes next. On each screen you will see two options: one will be the next word in the sentence, and one will not. </p><p><b>Select the word that continues the sentence by pressing 'e' (left-hand) for the word on the left or pressing 'i' (right-hand) for the word on the right.</b></p><p>Select the best word as quickly as you can, but without making too many errors. </p><div><p>Click \"Continue\" to start the experiment.</p></div>",
    response: 0,
    sentence: "foo",
    trial_type: "html-button-response",
    trial_index: 0,
    time_elapsed: 1586,
    internal_node_id: "0.0-0.0",
  },
  {
    rt: [
      1382, 838, 632, 508, 461, 537, 505, 471, 551, 484, 551, 578, 589, 766,
      844,
    ],
    cumrt: [
      1382, 838, 632, 508, 461, 537, 505, 471, 551, 484, 551, 578, 589, 766,
      844,
    ],
    correct: [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    words: [
      "David",
      "caught",
      "the",
      "fish",
      "he",
      "will",
      "cook",
      "tomorrow,",
      "but",
      "it",
      "is",
      "not",
      "his",
      "favorite",
      "kind.",
    ],
    distractors: [
      "x-x-x",
      "wild",
      "paced",
      "afford",
      "did",
      "hike",
      "is",
      "ask,",
      "bellow",
      "best",
      "he",
      "mock",
      "add",
      "sue",
      "finish.",
    ],
    order: [1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1],
    sentence:
      "David caught the fish he will cook tomorrow, but it is not his favorite kind.",
    type: "adverb_low",
    item: 2,
    trial_type: "maze",
    trial_index: 1,
    time_elapsed: 11292,
    internal_node_id: "0.0-1.0-0.0",
  },
  {
    rt: null,
    stimulus: "",
    response: null,
    trial_type: "html-button-response",
    trial_index: 2,
    time_elapsed: 12293,
    internal_node_id: "0.0-1.0-1.0",
  },
  {
    rt: [967, 475, 645, 548, 594, 506, 524, 612, 575, 635, 470, 614, 454, 830],
    cumrt: [
      967, 475, 645, 548, 594, 506, 524, 612, 1635, 635, 470, 614, 454, 830,
    ],
    correct: [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1],
    words: [
      "Anne",
      "will",
      "serve",
      "the",
      "apples",
      "she",
      "picked",
      "tomorrow,",
      "but",
      "she",
      "won't",
      "serve",
      "the",
      "plums.",
    ],
    distractors: [
      "x-x-x",
      "executive",
      "would",
      "stop",
      "another",
      "shred",
      "necessity",
      "tire,",
      "us",
      "him",
      "grotesque",
      "information",
      "anticipate",
      "typically.",
    ],
    order: [1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1],
    sentence:
      "Anne will serve the apples she picked tomorrow, but she won't serve the plums.",
    type: "adverb_high",
    item: 1,
    trial_type: "maze",
    trial_index: 3,
    time_elapsed: 21806,
    internal_node_id: "0.0-1.0-0.1",
  },
  {
    rt: null,
    stimulus: "",
    response: null,
    trial_type: "html-button-response",
    trial_index: 4,
    time_elapsed: 22807,
    internal_node_id: "0.0-1.0-1.1",
  },
  {
    rt: [521, 515, 449, 406, 534, 482, 783, 491, 611, 510, 501, 529, 468],
    cumrt: [521, 515, 449, 406, 534, 482, 783, 491, 611, 510, 501, 529, 468],
    correct: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    words: [
      "The",
      "brother",
      "of",
      "the",
      "bride",
      "who",
      "embarrassed",
      "himself",
      "at",
      "the",
      "wedding",
      "felt",
      "ashamed.",
    ],
    distractors: [
      "x-x-x",
      "including",
      "have",
      "laugh",
      "after",
      "go",
      "below",
      "comforted",
      "his",
      "bottle",
      "exhale",
      "tail",
      "building.",
    ],
    order: [1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0],
    sentence:
      "The brother of the bride who embarrassed himself at the wedding felt ashamed.",
    type: "relative_high",
    item: 4,
    trial_type: "maze",
    trial_index: 5,
    time_elapsed: 29607,
    internal_node_id: "0.0-1.0-0.2",
  },
  {
    rt: null,
    stimulus: "",
    response: null,
    trial_type: "html-button-response",
    trial_index: 6,
    time_elapsed: 30608,
    internal_node_id: "0.0-1.0-1.2",
  },
  {
    rt: [404, 390, 476, 413, 399, 560, 496, 371, 847, 679, 477, 615, 589],
    cumrt: [404, 390, 476, 413, 399, 560, 496, 371, 847, 679, 477, 615, 589],
    correct: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    words: [
      "The",
      "sister",
      "of",
      "the",
      "boy",
      "who",
      "taught",
      "himself",
      "advanced",
      "mathematics",
      "was",
      "very",
      "smart.",
    ],
    distractors: [
      "x-x-x",
      "know",
      "deposit",
      "await",
      "have",
      "done",
      "about",
      "been",
      "she",
      "raise",
      "upscale",
      "slopes",
      "instantly.",
    ],
    order: [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
    sentence:
      "The sister of the boy who taught himself advanced mathematics was very smart.",
    type: "relative_low",
    item: 3,
    trial_type: "maze",
    trial_index: 7,
    time_elapsed: 37326,
    internal_node_id: "0.0-1.0-0.3",
  },
  {
    rt: null,
    stimulus: "",
    response: null,
    trial_type: "html-button-response",
    trial_index: 8,
    time_elapsed: 38327,
    internal_node_id: "0.0-1.0-1.3",
  },
  {
    rt: 1764,
    stimulus: "<h2>All done! </h2>",
    response: 0,
    trial_type: "html-button-response",
    trial_index: 9,
    time_elapsed: 40091,
    internal_node_id: "0.0-2.0",
  },
];
